### ISSUE TITLE
Compare original vs rendered PDF

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-plateau#30]
Source issue: https://github.com/metanorma/metanorma-plateau/issues/2

Original PDF: https://github.com/metanorma/mn-samples-plateau/blob/main/reference-docs/plateau_doc_0001_ver04.pdf

Tasks:
- [x] decrease space between preface clause title and text
- [x] decrease space between paragraphs and list items
- [x] add left indent for inner numbered list
- [ ] redundant text in the 1st clause (https://github.com/metanorma/metanorma-plateau/issues/32)
- [x] missing underline style
- [x] figure/table number should be in bold
- [x] add space between terms
- [x] add space between definition list items
- [x] some paragraphs should be merged into one with line break (` +` markup)
- [x] each clause (except `2.`, if it's short, i.e. contain one paragraph) should be started at the new page
- [x] 3rd level title should be displayed with indent
- [x] english text in the figure/table titles should be in bold also
- [x] wrong `Table 4-2` rendering
- [x] character `d` after the `Table 4-4`
- [x] unordered list item label in the table is small dot
- [ ] 4th and 5th level sub-clause numbering (https://github.com/metanorma/metanorma-plateau/issues/33)
- [x] table legend (key) should be encoded as table footer (https://github.com/metanorma/mn-samples-plateau/issues/20)
- [x] missing footnote in the adoc (https://github.com/metanorma/mn-samples-plateau/issues/21)
